### ISSUE TITLE
*.pyc files in git repo?

### ISSUE THREAD

**Issue by guettli** [RedHatter/diodon-plugins#4]
There are pyc files in the git repo.

AFAIK this makes no sense.

See https://github.com/RedHatter/diodon-plugins/tree/master/waflib

**Comment by guettli** [comment]
Hello! Someone listening?

Why do you put .pyc files into a git repo? 

Maybe I am missing a good reason which I don't know up to now.

**Comment by RedHatter** [comment]
It is simply my inexperience with the waf build system.
